[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"


[[redirects]]
  from = "/register"
  to = "/.netlify/functions/register"
  status = 200
  force = true

[dev]
  autoLaunch = false



